---
output: "rho_uniform_onewg"
simulate: True
model: "gruyereO" # Can be gruyereO, gruyereBurden, gruyereSKAT 

jointly_trained_model: "/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gruyere/true/joint_burden_coding" # or path to a jointly trained model 
epochs: 300
n_samples: 50
test_prop: 0.001
cell: 'coding' # must be coding, OLIG2, LHX2, NEUN, or peripheralPU1nuclei
enformer_preds: False ### MAKE THIS TRUE FOR ALL CELL TYPES
enformer_path: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/ADSP_rare_variants_enformer_delta_scores_annotations_microglia.tsv.gz'
lof_preds: False

# fixed parameters
output_path: '/gpfs/commons/home/adas/gruyere/outputs/'
phenotype: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/phenotypes/36K_QC_filtered_final.csv'
gene_matrices: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/'
covariates: ['Sex','Age','apoe_e4','apoe_e2','PC1', 'PC2','PC3','PC4','PC5','PC6', 'PC7','PC8','PC9','PC10', 'Illumina_HiSeq_2000', 'Illumina_HiSeqX','Illumina_NovaSeq', 'Illumina', 'USUHS', 'USUHS/Miami','NYGC', 'MEDGENOME', 'Baylor', 'Broad', 'WashU', 'PRS_5'] 
covariate_interactions: True
ancestry: "ALL" # 'EUR', 'EAS', 'AFR', 'AMR', 'SAS' or "ALL"
maf_weights: "observed" # must be gnomad or observed
imputation: "fixed"
lr: 0.1
annotations: 'NMF_PREP' # can be "all", list of annotations, "none", or "NNMF" or "NMF_PREP"
wg_separate: True
alpha_gene: True
